cursor_shape beam
cursor_blink_interval -1
cursor_stop_blinking_after 10
cursor_trail 0

enabled_layouts tall,*

window_margin_width 4
window_border_width 2pt
single_window_margin_width 1

tab_bar_align left
tab_bar_min_tabs 1
tab_bar_style powerline
tab_bar_edge bottom
tab_bar_align left
tab_powerline_style round
tab_activity_symbol *
startup_session_window_state fullscreen

hide_window_decorations titlebar-only


window_padding_width 8


scrollback_lines 20000

wheel_scroll_multiplier 5


confirm_os_window_close 0


enable_audio_bell no
visual_bell_duration 0

remember_window_size yes
