# Theme
include themes/current-theme.conf

# Fonts
include fonts.conf

# Appearance
include appearance.conf

# Keyboard
include keyboard.conf

allow_remote_control yes

listen_on unix:/tmp/kitty-%n.sock
